baseURL = "https://vvasuki.github.io/"
languageCode = "en-us"
title = "विश्वासस्य जालक्षेत्रम् Vishvas Vasuki's website"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vvasuki/vvasuki.github.io/edit/hugo-source/content/"
  contactLink = "https://github.com/vvasuki/vvasuki.github.io/issues/new"
  env = "production"
  disqusShortcode = "vvasuki-site"

[markup.goldmark.renderer]
  unsafe= true